### PR TITLE
Added Tapa <market_entry>

### PR DESCRIPTION
**Pull request by marpontes**
Added Tapa [https://github.com/marpontes/tapa] <market_entry>

### CODE REVIEW

**Comment by pamval** [comment]
This looks really god, but I've got two remarks which I think you should address before publishing:

1. As soon as you install this, it applies one of your templates. I think this is incorrect, it should keep the default Pentaho image. Merely installing the plugin should not change the application behavior.
2. I do not see a menu item to access the plugin anywhere. The only way to access it is via the link in the welcome page. I think there should be a menu item somewhere that lets you access the plugin.

**Comment by marpontes** [comment]
Thanks, Pedro.

1. I can push the settings to have the plugin disabled by default, i'll do that.
2. Tapa can be accessed via its perspective. Is that a problem? I did that to get more vertical space.

**Comment by pamval** [comment]
1. No, I don't mean for the plugin to be disabled. I just think the default template should be the Pentaho one.

2. That's not a problem. I missed the perspective, sorry.  That works great.

**Comment by marpontes** [comment]
Oh i got it :) Gonna change that right away. Thank you again

**Comment by marpontes** [comment]
Hi, Pedro. Just did it. 

I've pushed this change to master, but i didn't generate a new release. I've just replaced the zipped package and the notes.

Could you please check it?

**Pull request merged**
