### PR TITLE
Update marketplace.xml

### PR DESCRIPTION
**Pull request by buggtb**

### CODE REVIEW

**Comment by eliofreitas** [comment]
Hello, This is an automated comment from our build system. Since this pull request originated from a user  not in the Pentaho organization, we will not proceed  with automatic validation of the pull request.  However, rest assured that it will be reviewed manually as soon  as we get the chance. Thanks for your contribution!

**Comment by buggtb** [comment]
Much more polite!

--------------

Director Meteorite.bi - Saiku Analytics Founder
Tel: +44(0)5603641316

(Thanks to the Saiku community we reached our Kickstart
<http://kickstarter.com/projects/2117053714/saiku-reporting-interactive-report-designer/>
goal, but you can always help by sponsoring the project
<http://www.meteorite.bi/products/saiku/sponsorship>)

**Comment by lucboudreau** [comment]
lol Tom, having fun teaching some manners to a machine? :)

**Comment by eliofreitas** [comment]
Hello, This is an automated comment from our build system. Since this pull request originated from a user  not in the Pentaho organization, we will not proceed  with automatic validation of the pull request.  However, rest assured that it will be reviewed manually as soon  as we get the chance. Thanks for your contribution!

**Comment by buggtb** [comment]
Thanks @eliofreitas you'd already told me that, I'm cool with waiting......

**Comment by eliofreitas** [comment]
Hello, This is an automated comment from our build system. Since this pull request originated from a user  not in the Pentaho organization, we will not proceed  with automatic validation of the pull request.  However, rest assured that it will be reviewed manually as soon  as we get the chance. Thanks for your contribution!

**Comment by buggtb** [comment]
Awww, now you're making me sad.

--------------

Director Meteorite.bi - Saiku Analytics Founder
Tel: +44(0)5603641316

(Thanks to the Saiku community we reached our Kickstart
<http://kickstarter.com/projects/2117053714/saiku-reporting-interactive-report-designer/>
goal, but you can always help by sponsoring the project
<http://www.meteorite.bi/products/saiku/sponsorship>)

**Comment by lucboudreau** [comment]
Looks like there's a bug with this script. Sorry for the chatter.

**Comment by pamval** [comment]
there there, Tom, no need to be sad. The bot is just over polite now. 

But we did listen to the community. See ?

**Comment by buggtb** [comment]
I never said you didn't! I like the bot it keeps me distracted from doing
productive work ;)

--------------

Director Meteorite.bi - Saiku Analytics Founder
Tel: +44(0)5603641316

(Thanks to the Saiku community we reached our Kickstart
<http://kickstarter.com/projects/2117053714/saiku-reporting-interactive-report-designer/>
goal, but you can always help by sponsoring the project
<http://www.meteorite.bi/products/saiku/sponsorship>)

**Comment by pamval** [comment]
It doesn't take much, does it ? :-P

**Comment by pmalves** [comment]
And that's true for both of you, I guess... :p

**Comment by pamval** [comment]
surprised it took you this long...

**Comment by pmalves** [comment]
Hey, I'm surprised at myself. Took a huge effort out of myself.

But I eventually gave up

**Pull request merged**
