### PR TITLE
waqe plugin

### PR DESCRIPTION
**Pull request by jortilles**
This is the first commit of the pentaho waqe plugin.

### CODE REVIEW

**Comment by pamval** [comment]
I get a bunch of server-side errors when trying to run this:
2015-10-12 14:10:32,152 ERROR [org.pentaho.di] 2015/10/12 14:10:32 - GetICATs 2.0 - ERROR (version 5.4.0.0-120, build 1 from 2015-05-23_15-23-20 by buildguy) : org.pentaho.di.core.exception.KettleException: 
2015/10/12 14:10:32 - GetICATs 2.0 - Error parsing string [Unexpected token END OF FILE at position 0.]!
2015/10/12 14:10:32 - GetICATs 2.0 - 
2015/10/12 14:10:32 - GetICATs 2.0 - 	at org.pentaho.di.trans.steps.jsoninput.JsonReader.readString(JsonReader.java:147)
2015/10/12 14:10:32 - GetICATs 2.0 - 	at org.pentaho.di.trans.steps.jsoninput.JsonInput.parseJson(JsonInput.java:272)
2015/10/12 14:10:32 - GetICATs 2.0 - 	at org.pentaho.di.trans.steps.jsoninput.JsonInput.readFileOrString(JsonInput.java:258)
2015/10/12 14:10:32 - GetICATs 2.0 - 	at org.pentaho.di.trans.steps.jsoninput.JsonInput.ReadNextString(JsonInput.java:165)
2015/10/12 14:10:32 - GetICATs 2.0 - 	at org.pentaho.di.trans.steps.jsoninput.JsonInput.getOneRow(JsonInput.java:396)
2015/10/12 14:10:32 - GetICATs 2.0 - 	at org.pentaho.di.trans.steps.jsoninput.JsonInput.processRow(JsonInput.java:344)
2015/10/12 14:10:32 - GetICATs 2.0 - 	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2015/10/12 14:10:32 - GetICATs 2.0 - 	at java.lang.Thread.run(Thread.java:745)

**Comment by jortilles** [comment]
I see the problem....

I'll solve it and provide a new zip.


Juanjo Ortilles - Open Business Analytics
twitter: jortilles
www.jortilles.com / es / cat

2015-10-12 20:14 GMT+02:00 Pedro Vale <notifications@github.com>:

**Comment by jortilles** [comment]
Can you try one more time?

I've fixed the bugs.

Thanks.

**Comment by jortilles** [comment]
:D Great!

**Pull request merged**
