### PR TITLE
PDI Sunrise Plugin

### PR DESCRIPTION
**Pull request by matthewtckr**

### CODE REVIEW

**Comment by pamval** [comment]
@matthewtckr can you reissue this pull request, Matt ?

thanks!

**Comment by mbatchelor** [comment]
Please rebase.

**Comment by matthewtckr** [comment]
@mbatchelor Rebased

**Comment by matthewtckr** [comment]
It looks like Wingman [needs a new entry for this project](https://github.com/pentaho/pentaho-wingman/blob/master/assembly/src/main/assembly/etc/wingman.json).

**Pull request merged**
