### PR TITLE
Added a new plugin

### PR DESCRIPTION
**Pull request by nhaquet**
Hi all,

Here's another pull request for my third plugin. It is my biggest one yet. This time, it is a sparkl plugin called Mondrian Translator. It takes some analysis schema xml, transforms it and generates property files in the pentaho webapp classpath for i18n internationalization.

I hope it goes well.

Have a nice week-end,

Nicolas Haquet

### CODE REVIEW

**Comment by pamval** [comment]
Hello. Your plugin id should match the folder name in system where your plugin will be (localizedmondrian in your case).

Also, plugin ids can not contain dot characters.

You can test your changes to marketplace.xml by pointing your pentaho installation to your branch of marketplace-metadata. You can edit settings.xml at system/marketplace and change the marketplace-site tag to 

<marketplace-site>
https://raw.githubusercontent.com/nhaquet/marketplace-metadata/master/marketplace.xml
</marketplace-site>

This will make the marketplace use your branch of metadata instead of the default one.

**Comment by pamval** [comment]
Hey. Tested this on a 5.2 build using Saiku and JPIvot and I'm unable to get the translated schema in the UI (I get the english defaults). I'm switching the language to fr in the PUC menu, after  installing the appropriate language pack. Should this work or am I missing a step ?

**Comment by nhaquet** [comment]
I corrected the id, sorry for the mistake.

I haven't tested the plugn with saiku just with regular analysis reports. Have you added the option in the mondrian.properties file? I suppose you have restarted the server and emptied the mondrian cache.

Can you see the property files in the WEB-INF/classes/com/pentaho/messages directory in your pentaho web app?

**Comment by pamval** [comment]
Ok, I do manage to see the translations using Pivot4j - looks real good and the installation is corrected.

However, I ask you to rebase your commit - I can't automatically merge it now and we'll avoid the merge commits you have here. Also, please squash your commits into a single one.

Thanks!

**Comment by nhaquet** [comment]
I'll delete my fork and start over then. It'll be easier this way since I didn't create a branch on my fork. I'm a noob ;o)

**Pull request closed without merging**
