### PR TITLE
Update Saiku Plugin to v3.90

### PR DESCRIPTION
**Pull request by RyanMcDonagh**

### CODE REVIEW

**Comment by pmalves** [comment]
This doesn't seem right. The download points to the full server that
doesn't even match a pentaho plugin...

You guys sure about this?

**Comment by RyanMcDonagh** [comment]
My mistake! Will sort this now.

**Comment by RyanMcDonagh** [comment]
Fixed! Sorry!

**Comment by buggtb** [comment]
This is what happens when you let the newbies loose!! (and have a migraine so you can't read the screen)

**Pull request merged**
