### PR TITLE
Update description for Self Service BI plugin

### PR DESCRIPTION
**Pull request by SPECUSA**
Hello @pamval,
Please review and update the description for our plugin, Self Service BI

### CODE REVIEW

**Comment by pamval** [comment]
this has merge conflicts. Please rebase.

**Comment by SPECUSA** [comment]
hello @pamval 
Resolved that merge conflicts by rebase it again.
Please review and update the description for our plugin, Self Service BI

**Comment by SPECUSA** [comment]
Hello @pamval
I was wondering if we can add hyperlink in the plugin description or not?
Here I've added link for user guide of plugin,but user has to copy and paste to open it, so is there any way we can add hyperlink in description?
and thanks for update description

**Comment by pamval** [comment]
Use a CDATA tag to encapsulate the description and then use a href tag. See
here for example:

https://github.com/pentaho/marketplace-metadata/blob/master/marketplace.xml#
L1129
Pedro Vale
Dev Lead
phone: +351 214870076       fax: +351 218041985
Vila Internacional
ED.2 1º Andar
2750-047 Aldeia de Juso, Portugal
pentaho.com


From:  SPEC-USA <notifications@github.com>
Reply-To:  pentaho/marketplace-metadata
<reply+00054d542b28d7e26347bca71134c1516fdaeb813ce551eb92cf000000011212458f9
2a169ce065d287b@reply.github.com>
Date:  quinta-feira, 17 de Setembro de 2015 às 10:10
To:  pentaho/marketplace-metadata <marketplace-metadata@noreply.github.com>
Cc:  Pedro Vale <pedro.vale@webdetails.pt>
Subject:  Re: [marketplace-metadata] Update description for Self Service BI
plugin (#379)


Hello @pamval <https://github.com/pamval>
I was wondering if we can add hyperlink in the plugin description or not?
Here I've added link for user guide of plugin,but user has to copy and paste
to open it, so is there any way we can add hyperlink in description?
and thanks for update description


Reply to this email directly or view it on GitHub
<https://github.com/pentaho/marketplace-metadata/pull/379#issuecomment-14101
8581> .

**Comment by SPECUSA** [comment]
Thanks @pamval , for your quick reply

**Pull request merged**
