### PR TITLE
Initialize Essbase Plugin

### PR DESCRIPTION
**Pull request by bcolas**
Adding new plugin for Essbase to Pentaho marketplace : 
- Datasource connexion wizard
- Data output step
- Data input step
- MAXL Job entry

(https://github.com/bcolas/PDIEssbasePlugin/wiki)

### CODE REVIEW

**Comment by mattyb149** [comment]
The install didn't work for me, I believe it's because the download URL for the ZIP points at the GitHub page, not the raw ZIP itself.

**Comment by bcolas** [comment]
I change the distribution of the zipped file to https://github.com/bcolas/PDIEssbasePlugin/releases/download/1.0/kettle-essbase-plugin-5.2.zip

**Comment by mattyb149** [comment]
Installation is working now, I did see some message labels in the dialog that were not recognized, such as OlapInputDialog.Stepame and EssbaseOlapInput.Position.Label. If you like I can merge it as-is, or if you'd like to update it I can merge it afterwards.  Thanks!

**Comment by bcolas** [comment]
Matt, you can merge as is. I am fixing the problems you detected right now.

**Pull request merged**
