### PR TITLE
Including STPivot4 in pentaho marketplace

### PR DESCRIPTION
**Pull request by joseraulperezrodriguez**
We have developed this plugin to community usage. Willing to see it available on marketplace next weeks.

### CODE REVIEW

**Comment by joseraulperezrodriguez** [comment]
Hi pentaho, could you please take a look at our plugin.

**Comment by pamval** [comment]
Sorry, I missed this. Could you please rebase? It is showing some conflicts.

Thanks!

**Comment by joseraulperezrodriguez** [comment]
Thanks @pamval, I have updated the pull request solving the conflict.

**Comment by joseraulperezrodriguez** [comment]
@pamval Thanks.
When the plugin will be available in marketplace?

**Comment by pmalves** [comment]
Now on the product...

And tomorrow on the marketplace website

**Pull request merged**
