### PR TITLE
New PDI plugins for validate NIP, REGON, PESEL tax numbers

### PR DESCRIPTION
**Pull request by rafaljot**

### CODE REVIEW

**Comment by mattyb149** [comment]
The NIP validator step has a missing title (displayed as !NipValidatorStep.Shell.Title!), and although a "Sanmargar" category is added to the transformation step categories (on the left design pane), the entry (or the plugin(s)) add another with a missing label (displayed as !Steps.Category.Name!). This second one may be a result of a missing localized string here:

https://github.com/Sanmargar/sdtt/blob/master/sanmargar-sdtt-kettle-nip_pesel_regon_validator/src/pl/sanmargar/sdtt/kettle/nipvalidator/NIPValidatorMeta.java#L55

**Comment by rafaljot** [comment]
I found one more bug.

**Comment by rafaljot** [comment]
Simple mistake. It is funny because it appears on one machine and not on another.

**Comment by mattyb149** [comment]
Do you mind squashing the commits down to 1, and rebasing against the latest master branch? It will enable us to merge this pull request. Thanks!

**Comment by rafaljot** [comment]
Matt, of course. Already done.

**Pull request closed without merging**
