### PR TITLE
Actualización de imágenes del plugin

### PR DESCRIPTION
**Pull request by BahiaSoftware**

### CODE REVIEW

**Comment by pamval** [comment]
@BahiaSoftware please rebase. This pull request is not mergeable. thanks.

**Comment by BahiaSoftware** [comment]
Hello @pamval ,

We have seen that the pull request is not mergeable, but we think it is for the change of location the <market_entry> of the BayInspect plugin.
We made a mistake with the location, this can not be corrected?

Thanks in advance and regards

**Comment by pamval** [comment]
no, the conflict occurred because you did not pull from pentaho/marketplace-metadata before committing the new change. 

Anyway, that's ok. I manually merged this.

**Comment by BahiaSoftware** [comment]
ok, thank you very much and apologize for the inconvenience

**Pull request closed without merging**
