### PR TITLE
Add BayInspect Plugin

### PR DESCRIPTION
**Pull request by BahiaSoftware**

### CODE REVIEW

**Comment by pamval** [comment]
hello @BahiaSoftware.

This is not a valid pull request. You're adding the marketentry tag outside of the root market tag.

Please review.

btw, You can call ant from the project folder to make sure your changes result in a valid xml that conforms to the xsd.


Thanks!

**Comment by BahiaSoftware** [comment]
Hello @pamval,

Apologize for the error, we have uploaded corrected marketplace.xml

Thanks in advance and regards.

**Comment by pamval** [comment]
@BahiaSoftware sorry but we have another issue now. The installation procedure is creating a folder called BayInspect-master and that is not correct. The plugin folder name must match the plugin id (in this case it is BayInspect).

thanks!

**Comment by BahiaSoftware** [comment]
Hello @pamval,

We have created the appropriate .zip to install the plugin and updated package_url in marketplace.xml for download.

Thanks and regards.

**Comment by BahiaSoftware** [comment]
Thancks very much and regards!

**Pull request merged**
