### PR TITLE
Add: PDI UniqueList Plugin

### PR DESCRIPTION
**Pull request by overtron**
This step allows you to de-duplicate concatenated lists.

## Use Cases
When moving from normalized to denormalized data or dealing with attributes of an entity you may want a unique list of delimited values. For example, imagine you have a list of all the countries a person has visited, one entry for each city
```
England,Spain,Spain,Belgium,Belgium,Trinidad,Trinidad,Mexico,Trinidad
```
Now, imagine you want each entry in the list to be unique. You can pass the field to the Unique List step and get that result.
```
England,Spain,Belgium,Trinidad,Mexico
```

The source can be found [here](https://github.com/graphiq-data/pdi-uniquelist-plugin)

### CODE REVIEW

**Comment by mattyb149** [comment]
Please rebase against the latest master branch, thanks!

**Comment by overtron** [comment]
Thanks @mattyb149 this one is updated

**Comment by overtron** [comment]
last one is ready to go. thank you for working through all of these!

**Comment by mattyb149** [comment]
Uninstall doesn't work for this one, I believe the plugin ID in the marketplace entry has to match the root folder name in the ZIP file. Installation, dialog open, Get Fields all work fine. Want me to merge as-is?

**Comment by mattyb149** [comment]
Argh, sorry, I ended up merging another one, already forgot about the rebase problems :(

**Comment by overtron** [comment]
Thanks for the heads up. Would've fixed Friday, but was out of office. I was able to successfully install and uninstall with this version.

**Pull request merged**
