### PR TITLE
 Merge branch 'master' of https://github.com/pentaho/marketplace-metadata

### PR DESCRIPTION
**Pull request by SPECUSA**
Pentaho 8.1 release and bug fixes.

### CODE REVIEW

**Comment by pamval** [comment]
hello, can you please rebase your changes?

**Comment by SPECUSA** [comment]
> hello, can you please rebase your changes?

We have rebased the branch.

**Comment by SPECUSA** [comment]
> > hello, can you please rebase your changes?
> 
> We have rebased the branch.

@pamval Can you please merge this branch.

**Comment by pamval** [comment]
This still shows up as having conflicts and there's a big list of commits here that looks as a result of a merge.

Can you  get a clean master branch and apply your changes on top of that? 

Thanks!

**Comment by pamval** [comment]
Yes, it does show up as having conflicts.

If you take a look at the commit list in this pr, you'll notice there are commits from Dec 2017. That tells me that you're trying to do a pull request from a local branch of yours that is not synced with our master branch. 

You need to start with a clean master branch that is synced with this repository master branch and then apply your changes. It's probably best if you try to do that in a new pull request.

**Pull request closed without merging**
